version: '3.8'

services:
  screenmatch-frases:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://dpg-cu878ttsvqrc73b78btg-a.oregon-postgres.render.com/screenmatch_frases
      DB_USER: screenmatch_frases_user
      DB_PASSWORD: bjn2MDhDslsg4DohEsZOfLx31f8sj6YJ
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: screenmatch_frases_user
      POSTGRES_PASSWORD: bjn2MDhDslsg4DohEsZOfLx31f8sj6YJ
      POSTGRES_DB: screenmatch_frases
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 5s
      retries: 5